<?xml version="1.0" encoding="utf-8"?><Database Name="CurtDev" Class="CurtDevDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=CurtDev;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CurtDevConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="catID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="parentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="catTitle" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="shortDesc" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="longDesc" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="isLifestyle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="codeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ColorCode" Member="ColorCodes">
    <Type Name="ColorCode">
      <Column Name="codeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="font" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="menuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menu_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="isPrimary" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="display_name" Type="System.String" DbType="VarChar(255) NULL" CanBeNull="true" />
      <Column Name="requireAuthentication" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="showOnSitemap" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Menu_Menu_SiteContent" Member="Menu_SiteContents" ThisKey="menuID" OtherKey="menuID" Type="Menu_SiteContent" />
    </Type>
  </Table>
  <Table Name="dbo.Menu_SiteContent" Member="Menu_SiteContents">
    <Type Name="Menu_SiteContent">
      <Column Name="menuContentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="menuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="contentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="menuSort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="menuTitle" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="menuLink" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="parentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_SiteContent_Menu_SiteContent" Member="Menu_SiteContents" ThisKey="menuContentID" OtherKey="parentID" Type="Menu_SiteContent" />
      <Association Name="Menu_Menu_SiteContent" Member="Menu" ThisKey="menuID" OtherKey="menuID" Type="Menu" IsForeignKey="true" />
      <Association Name="Menu_SiteContent_Menu_SiteContent" Member="Menu_SiteContent1" ThisKey="parentID" OtherKey="menuContentID" Type="Menu_SiteContent" IsForeignKey="true" />
      <Association Name="SiteContent_Menu_SiteContent" Member="SiteContent" ThisKey="contentID" OtherKey="contentID" Type="SiteContent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiteContentRevision" Member="SiteContentRevisions">
    <Type Name="SiteContentRevision">
      <Column Name="revisionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="content_text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="createdOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SiteContent_SiteContentRevision" Member="SiteContent" ThisKey="contentID" OtherKey="contentID" Type="SiteContent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactReceiver" Member="ContactReceivers">
    <Type Name="ContactReceiver">
      <Column Name="contactReceiverID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="ContactReceiver_ContactReceiver_ContactType" Member="ContactReceiver_ContactTypes" ThisKey="contactReceiverID" OtherKey="contactReceiverID" Type="ContactReceiver_ContactType" />
    </Type>
  </Table>
  <Table Name="dbo.FAQ" Member="FAQs">
    <Type Name="FAQ">
      <Column Name="faqID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="question" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="answer" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NewsItem" Member="NewsItems">
    <Type Name="NewsItem">
      <Column Name="newsItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="lead" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="publishStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="publishEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="slug" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogPost_BlogCategory" Member="BlogPost_BlogCategories">
    <Type Name="BlogPost_BlogCategory">
      <Column Name="postCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="blogPostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="blogCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BlogPost_BlogPost_BlogCategory" Member="BlogPost" ThisKey="blogPostID" OtherKey="blogPostID" Type="BlogPost" IsForeignKey="true" />
      <Association Name="BlogCategory_BlogPost_BlogCategory" Member="BlogCategory" ThisKey="blogCategoryID" OtherKey="blogCategoryID" Type="BlogCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogPosts" Member="BlogPosts">
    <Type Name="BlogPost">
      <Column Name="blogPostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="post_title" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="slug" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="publishedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="meta_title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keywords" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="post_text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="BlogPost_BlogPost_BlogCategory" Member="BlogPost_BlogCategories" ThisKey="blogPostID" OtherKey="blogPostID" Type="BlogPost_BlogCategory" />
      <Association Name="BlogPost_Comment" Member="Comments" ThisKey="blogPostID" OtherKey="blogPostID" Type="Comment" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="commentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="blogPostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="comment_text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BlogPost_Comment" Member="BlogPost" ThisKey="blogPostID" OtherKey="blogPostID" Type="BlogPost" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BlogCategories" Member="BlogCategories">
    <Type Name="BlogCategory">
      <Column Name="blogCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="slug" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="BlogCategory_BlogPost_BlogCategory" Member="BlogPost_BlogCategories" ThisKey="blogCategoryID" OtherKey="blogCategoryID" Type="BlogPost_BlogCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Country" Member="Countries">
    <Type Name="Country">
      <Column Name="countryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="abbr" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Country_State" Member="States" AccessModifier="Internal" ThisKey="countryID" OtherKey="countryID" Type="State" />
    </Type>
  </Table>
  <Table Name="dbo.States" Member="States">
    <Type Name="State">
      <Column Name="stateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="state" Member="state1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="abbr" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="countryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="State_CustomerLocation" Member="CustomerLocations" AccessModifier="Internal" ThisKey="stateID" OtherKey="stateID" Type="CustomerLocation" />
      <Association Name="State_Customer" Member="Customers" AccessModifier="Internal" ThisKey="stateID" OtherKey="stateID" Type="Customer" />
      <Association Name="Country_State" Member="Country" ThisKey="countryID" OtherKey="countryID" Type="Country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerLocations" Member="CustomerLocations">
    <Type Name="CustomerLocation">
      <Column Name="locationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="stateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="cust_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="contact_person" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="isprimary" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="postalCode" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Customer_CustomerLocation" Member="Customer" AccessModifier="Internal" ThisKey="cust_id" OtherKey="cust_id" Type="Customer" IsForeignKey="true" />
      <Association Name="State_CustomerLocation" Member="State" ThisKey="stateID" OtherKey="stateID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiteContent" Member="SiteContents">
    <Type Name="SiteContent">
      <Column Name="contentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="content_type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="page_title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lastModified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="meta_title" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="meta_description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="keywords" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="isPrimary" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="published" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="slug" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="requireAuthentication" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="canonical" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="SiteContent_Menu_SiteContent" Member="Menu_SiteContents" ThisKey="contentID" OtherKey="contentID" Type="Menu_SiteContent" />
      <Association Name="SiteContent_SiteContentRevision" Member="SiteContentRevisions" ThisKey="contentID" OtherKey="contentID" Type="SiteContentRevision" />
    </Type>
  </Table>
  <Table Name="dbo.BusinessClass" Member="BusinessClasses">
    <Type Name="BusinessClass">
      <Column Name="BusinessClassID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="showOnWebsite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactType" Member="ContactTypes">
    <Type Name="ContactType">
      <Column Name="contactTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="ContactType_ContactReceiver_ContactType" Member="ContactReceiver_ContactTypes" ThisKey="contactTypeID" OtherKey="contactTypeID" Type="ContactReceiver_ContactType" />
    </Type>
  </Table>
  <Table Name="dbo.ContactReceiver_ContactType" Member="ContactReceiver_ContactTypes">
    <Type Name="ContactReceiver_ContactType">
      <Column Name="receiverTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="contactReceiverID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="contactTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ContactReceiver_ContactReceiver_ContactType" Member="ContactReceiver" ThisKey="contactReceiverID" OtherKey="contactReceiverID" Type="ContactReceiver" IsForeignKey="true" />
      <Association Name="ContactType_ContactReceiver_ContactType" Member="ContactType" ThisKey="contactTypeID" OtherKey="contactTypeID" Type="ContactType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Testimonial" Member="Testimonials">
    <Type Name="Testimonial">
      <Column Name="testimonialID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rating" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="testimonial" Member="testimonial1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DealerTypes" Member="DealerTypes">
    <Type Name="DealerType">
      <Column Name="dealer_type" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="online" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="show" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="label" Type="System.String" DbType="VarChar(300) NULL" CanBeNull="false" />
      <Association Name="DealerType_MapIcon" Member="MapIcons" ThisKey="dealer_type" OtherKey="dealer_type" Type="MapIcon" />
      <Association Name="Customer_DealerType" Member="Customer" AccessModifier="Internal" ThisKey="dealer_type" OtherKey="dealer_type" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="cust_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="stateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="contact_person" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="dealer_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="longitude" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="website" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="customerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isDummy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="parentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="searchURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="address2" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="postal_code" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="mCodeID" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="salesRepID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="showWebsite" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="eLocalURL" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Customer_CustomerLocation" Member="CustomerLocations" ThisKey="cust_id" OtherKey="cust_id" Type="CustomerLocation" />
      <Association Name="Customer_DealerType" Member="DealerType" ThisKey="dealer_type" OtherKey="dealer_type" Type="DealerType" Cardinality="One" />
      <Association Name="Customer_DealerTier" Member="DealerTier" ThisKey="tier" OtherKey="ID" Type="DealerTier" Cardinality="One" />
      <Association Name="State_Customer" Member="State" ThisKey="stateID" OtherKey="stateID" Type="State" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lifestyle_Trailer" Member="Lifestyle_Trailers">
    <Type Name="Lifestyle_Trailer">
      <Column Name="lifestyleTrailerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="catID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trailerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Trailer" Member="Trailers">
    <Type Name="Trailer">
      <Column Name="trailerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GTW" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="hitchClass" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="shortDesc" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Video" Member="Videos">
    <Type Name="Video">
      <Column Name="videoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="embed_link" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="dateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) null" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(max) null" CanBeNull="true" />
      <Column Name="youtubeID" Type="System.String" DbType="VarChar(255) NULL" CanBeNull="true" />
      <Column Name="watchpage" Type="System.String" DbType="VarChar(255) NULL" CanBeNull="true" />
      <Column Name="screenshot" Type="System.String" DbType="VarChar(255) NULL" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IPBlock" Member="IPBlocks">
    <Type Name="IPBlock">
      <Column Name="blockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="reason" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ForumGroup" Member="ForumGroups">
    <Type Name="ForumGroup">
      <Column Name="forumGroupID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ForumGroup_ForumTopic" Member="ForumTopics" ThisKey="forumGroupID" OtherKey="TopicGroupID" Type="ForumTopic" />
    </Type>
  </Table>
  <Table Name="dbo.ForumTopic" Member="ForumTopics">
    <Type Name="ForumTopic">
      <Column Name="topicID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TopicGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="ForumTopic_ForumThread" Member="ForumThreads" ThisKey="topicID" OtherKey="topicID" Type="ForumThread" />
      <Association Name="ForumGroup_ForumTopic" Member="ForumGroup" ThisKey="TopicGroupID" OtherKey="forumGroupID" Type="ForumGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForumPost" Member="ForumPosts">
    <Type Name="ForumPost">
      <Column Name="postID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="parentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="threadID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="post" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="notify" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="approved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="flag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sticky" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ForumThread_ForumPost" Member="ForumThread" ThisKey="threadID" OtherKey="threadID" Type="ForumThread" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForumThread" Member="ForumThreads">
    <Type Name="ForumThread">
      <Column Name="threadID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="topicID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="closed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ForumThread_ForumPost" Member="ForumPosts" ThisKey="threadID" OtherKey="threadID" Type="ForumPost" />
      <Association Name="ForumTopic_ForumThread" Member="ForumTopic" ThisKey="topicID" OtherKey="topicID" Type="ForumTopic" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Contact" Member="Contacts">
    <Type Name="Contact">
      <Column Name="contactID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="subject" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="address1" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="address2" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="postalcode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TwitterLog" Member="TwitterLogs">
    <Type Name="TwitterLog">
      <Column Name="tweetLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lastUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="tweets" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tweets" Member="Tweets">
    <Type Name="Tweet">
      <Column Name="tweetID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="twitterTweetID" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="tweet" Member="tweet1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="postDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="twitterUserID" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="screenName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="profilePhoto" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DealerTiers" Member="DealerTiers">
    <Type Name="DealerTier">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tier" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DealerTier_MapIcon" Member="MapIcons" AccessModifier="Internal" ThisKey="ID" OtherKey="tier" Type="MapIcon" />
      <Association Name="Customer_DealerTier" Member="Customer" AccessModifier="Internal" ThisKey="ID" OtherKey="tier" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapIcons" Member="MapIcons">
    <Type Name="MapIcon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dealer_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mapicon" Member="mapicon1" Type="System.String" DbType="VarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="mapiconshadow" Type="System.String" DbType="VarChar(300) NULL" CanBeNull="false" />
      <Association Name="DealerType_MapIcon" Member="DealerType" AccessModifier="Internal" ThisKey="dealer_type" OtherKey="dealer_type" Type="DealerType" IsForeignKey="true" />
      <Association Name="DealerTier_MapIcon" Member="DealerTier" AccessModifier="Internal" ThisKey="tier" OtherKey="ID" Type="DealerTier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MapPolygon" Member="MapPolygons">
    <Type Name="MapPolygon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="stateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MapPolygon_MapPolygonCoordinate" Member="MapPolygonCoordinates" ThisKey="ID" OtherKey="MapPolygonID" Type="MapPolygonCoordinate" />
    </Type>
  </Table>
  <Table Name="dbo.MapPolygonCoordinates" Member="MapPolygonCoordinates">
    <Type Name="MapPolygonCoordinate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MapPolygonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="MapPolygon_MapPolygonCoordinate" Member="MapPolygon" AccessModifier="Internal" ThisKey="MapPolygonID" OtherKey="ID" Type="MapPolygon" IsForeignKey="true" />
    </Type>
  </Table>
</Database>